model_type: S3D #can provide any name
device: cuda # cuda for gpu or cpu 
datasets:
  train:
    data_root: /work/21013187/phuoc_sign/dataraw_train #root_folder have npy file
    # data loader
    num_workers: 8
    batch_size: 8
    use_sampler: True
    save_class_name: /work/21013187/phuoc_sign/experiments/class_name.csv
    augument: 
      rotation: 13 #(-n to n)
      color: 
        - 0.2 #brightness
        - 0.2 # contrast 
        - 0.2 #saturation
        - 0.2 #hue
      h_flip: 0.5 #hori flip
      translate:
        max_x: 0.2
        max_y: 0.2
      gausian_noise:
        mean: 0
        std: 25
  val:
    data_root: /work/21013187/phuoc_sign/dataraw
    num_workers: 8
    batch_size: 8
    use_sampler: True

net:
  type: S3D_arch
  num_classes: 1001
  pretrained: True
  dropout: 0.2

# path
path:
  pretrain_model: /work/21013187/phuoc_sign/experiments/models/iter_5000.pth
# training settings
train:
  #use Adam optimizer
  lr: !!float 2e-5 
  weight_decay: 0
  total_iter: 30000

  scheduler:
    type: MultiStepRestartLR
    milestones: [200000, 250000, 275000, 287500]
    gamma: 0.5

val:
 val_freq: 1000
 metrics:
    precision: # metric name can provide any name
     type: calculate_precision
    f1: # metric name
     type: calculate_f1
    recall:
      type: caculate_recall

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: 500
  save_folder: /work/21013187/phuoc_sign/experiments/models2


