model_type: S3D_model #can provide any name
device: cuda # cuda for gpu or cpu 
datasets:
  train:
    name: slovo #can provid any name
    dataroot_path: D:/phuoc_sign/dataset/raw_data #root_folder have npy file
    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
  val:
    name: slovo
    dataroot_path: D:/phuoc_sign/dataset/raw_data
# path
path:
  pretrain_model: ~
# training settings
train:
  #use Adam optimizer
  lr: !!float 1e-4 
  weight_decay: 0
  total_iter: 300000

  scheduler:
    type: MultiStepLR
    milestones: [200000, 250000, 275000, 287500]
    gamma: 0.5

val:
 val_freq: !!float 5e4
 metrics:
    precision: # metric name can provide any name
     type: calculate_precision
    f1: # metric name
     type: calculate_f1
    recall:
      type: caculate_recall

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4


