model_type: S3D #can provide any name
device: cuda # cuda for gpu or cpu 
datasets:
  train:
    data_root: /work/21013187/phuoc_sign/dataraw #root_folder have npy file
    # data loader
    num_workers: 4
    batch_size: 8
  val:
    data_root: /work/21013187/phuoc_sign/dataraw
    num_workers: 4
    batch_size: 8
net:
  type: S3D_arch
  num_classes: 2
  pretrained: False
  dropout: 0.2
# path
path:
  pretrain_model: ~
# training settings
train:
  #use Adam optimizer
  lr: !!float 1e-4 
  weight_decay: 0
  total_iter: 300000

  scheduler:
    type: MultiStepRestartLR
    milestones: [200000, 250000, 275000, 287500]
    gamma: 0.5

val:
 val_freq: 1
 metrics:
    precision: # metric name can provide any name
     type: calculate_precision
    f1: # metric name
     type: calculate_f1
    recall:
      type: caculate_recall

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 1
  save_folder: /work/21013187/phuoc_sign/experiments/models


