model_type: S3D #can provide any name
device: cuda # cuda for gpu or cpu 
datasets:
  train:
    data_root:   /work/21013187/phuoc_sign/dataset/heatmap_input_train_raw  # data loader
    num_workers: 8
    batch_size: 8
    save_class_name: /work/21013187/phuoc_sign/experiments/heatmap_label.csv
    use_sampler: False
    augument:
      rotation: 10 #(-n to n)
      translate:
        max_x: 0.1
        max_y: 0.1
  val:
    data_root: /work/21013187/phuoc_sign/dataset/heatmap_input_train_raw
    num_workers: 8
    batch_size: 8
    use_sampler: False

net:
  type: S3D_arch
  num_classes: 20
  pretrained: True
  dropout: 0.2
  freezing_layer: 1

# path
path:
  pretrain_model: "/work/21013187/phuoc_sign/experiments/19_action__model/iter_1660.pth"
# training settings
train:
  #use Adam optimizer
  lr: !!float 2e-5 
  weight_decay: 0
  total_iter: 30000

  scheduler:
    type: MultiStepRestartLR
    milestones: [200000, 250000, 275000, 287500]
    gamma: 0.5

val:
 val_freq: 5
 metrics:
    precision: # metric name can provide any name
     type: calculate_precision
    f1: # metric name
     type: calculate_f1
    recall:
      type: caculate_recall

# logging settings
logger:
  print_freq: 1
  save_checkpoint_freq: 100
  save_folder: /work/21013187/phuoc_sign/experiments/19_action__model


